bool        MaxDistance_valid      
bool        SensorID_valid
bool        RadarPower_valid        
bool        OutputType_valid
bool        SendQuality_valid
bool        SendExtInfo_valid
bool        SortIndex_valid
bool        StoreInNVM_valid
uint16      MaxDistance
uint8       SensorID
uint8       OutputType
uint8       RadarPower

bool        CtrlRelay_valid
bool        CtrlRelay
bool        SendQuality
bool        SendExtInfo
uint8       SortIndex
bool        StoreInNVM

bool        RCS_Threshold_valid
uint8       RCS_Threshold
