bool        NVMReadStatus
bool        NVMwriteStatus
uint16      MaxDistanceCfg
bool        Persistent_Error
bool        Interference
bool        Temperature_Error
bool        Temporary_Error
bool        Voltage_Error
uint8       SensorID
uint8       SortIndex
uint8       RadarPowerCfg
bool        CtrlRelayCfg
uint8       OutputTypeCfg
bool        SendQualityCfg
bool        SendExtInfoCfg
uint8       MotionRxState
uint8       RCS_Threshold


